name: interpretable-machine-learning
channels:
  - conda-forge
  - ibmdecisionoptimization
  - defaults
dependencies:
  - python=3.7
  - pandas
  - pip
  - jupyter
  - nb_conda_kernels
  - ipykernel
  - numpy=1.20.1
  - scikit-learn
  - pyzmq=20
  - matplotlib
  - pyyaml
  - pip:
    - interpret
  